#!/usr/bin/python3

#SPDX-FileCopyrightText: 2022 Ryuichi Ueda <s22c1103zx@s.chibakoudai.jp>

import sys

ans = 0
for line in sys.stdin:
    try:
        ans += int(line)
    except:
        ans += float(line)

print(ans)
