#!/usr/bin/python3

import sys

#引数が数字であるか判別
def char_or_num(x):
    if isinstance(x, int):
        return True
    elif isinstance(x, str) and x.isdigit():
        return True
    else:
        return False

x = 0
pass_num = [0] * 10

for n in sys.argv[1:]:

    if char_or_num(n):

        num = int(n) - 7

        if num < 0:
            num *= -1
            pass_num[x] = num
            x += 1
        else:
            pass_num[x] = num
            x += 1
    else:
        print("数字を入力してください")
        sys.exit()

print(pass_num[:x])
